# 선형대수학

* 기하학적인 것을 숫자로 표현하기 위한 것
* 싸이킷 설치 
* pip install scikit-learn
* 벡터, 행렬
    - 스칼라 값의 크기
    - 벡터 방향을 가진 값
    - 선형대수학에서는 1차원 행렬을 벡터라고한다. (차원은 벡터의 길이, 요소는 벡터의 차원 ex. array([1, 5, -4]) 는 3차원 벡터 길이는 1)
    - 1차원 배열 : 벡터
    - 2차원 배열 : 행렬
    - 3차원 이상의 배열 : 텐서(Tensor)
* 내적 
    - 방향이 다른 두 벡터의 곱, 두 벡터가 얼마나 비슷한가
    - 내적 결과는 방향이 없다 (스칼라) a dot b = b dot a 
    - 벡터, 행렬, 텐서의 내적(Inner Product, Dot Product)
    - np.dot(a, b)
    - 행렬의 내적 
        - 행, 열 각각의 벡터를 내적한 값을 요소로 가지는 행렬
        - A dot B = C  A(m x n) dot B(n x r) = C(m x r)
        - A의 열과 B의 행이 같아야 한다.
    - 인공지능에서는 내적과 덧셈으로 모든 데이터들의 상관관계를 구한다. 나머지 연산은 의미가 없다.
    
* 넷플릭스등 맞춤형 추천 알고리즘에 쓰인다
    - 평점, 댓글 데이터를 이용해서 비슷한 데이터 군을 모으고 평균등과 비교해서 유사도에 따라 추천

In [1]:
import numpy as np

In [6]:
vector1 = np.array([1, 5, -4])

print(vector1)

array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

print(array1)

[ 1  5 -4]
[[1 2 3]
 [4 5 6]]


In [27]:
# 내적
v1 = np.array([1, 2, 3])
v2 = np.array([5, 0, -7])
print(np.dot(v1, v2))

v3 = np.array([5, 0])
v4 = np.array([0, 4])
print(np.dot(v3, v4))

v5 = np.array([5, 0])
v6 = np.array([4, 0])
print(np.dot(v5, v6))

v7 = np.array([-2, 4])
v8 = np.array([5, 0])
print(np.dot(v7, v8))
print(np.dot(v8, v7))

v9 = np.array([5, 0])
v10 = np.array([4, 6])
print(np.dot(v9, v10))

-16
0
20
-10
-10
20


In [32]:
# 행렬 내적
arr1 = np.array([[1, 2],  # 2차원 벡터가 3개 있다 혹은 3차원 벡터가 2개 있다 (전치)
                 [3, 4],
                 [5, 6]])

arr2 = np.array([[6, 23],
                 [-1, 7],
                 [8, 9]])

# 행렬의 내적
# 3,2 행렬 2개를 내적, 전치해서 앞의 열, 뒤의 행 값을 맞춰 준다.

print(arr2.T)
print(np.dot(arr1, arr2.T))

print(arr1.T)
print(np.dot(arr1.T, arr2))

[[ 6 -1  8]
 [23  7  9]]
[[ 52  13  26]
 [110  25  60]
 [168  37  94]]
[[1 3 5]
 [2 4 6]]
[[ 43  89]
 [ 56 128]]


In [42]:
# scikiLearn
from sklearn.datasets import load_iris

iris = load_iris() # 붓꽃 데이터, 품좀마다 차이 (꽃받침 길이, 폭 등)를 모아놓은 데이터

print(iris) # dictionary 키와 밸류  data : 꽃의 길이, target : 꽃의 품종(숫자), target_name : 품종명, ...

# 인공지능에서는 data를 x target을 y로 표현

iris['data'] # iris.data
iris.target # iris['target']

X = iris.data
Y = iris.target


{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [46]:
print(iris.target_names)
Y == 0 
# boolean indexing
X[Y == 0]  # setosa

['setosa' 'versicolor' 'virginica']


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [56]:
# 데이터의 통계

X[Y == 0].mean()
print('평균 :', X[Y == 0].mean(axis = 0)) # Y == 0 'setosa'들의 각 data 값의 평균값
print('표준편차 :', X[Y == 0].std(axis = 0)) # 표준편차

for i in range(3) :    # 각 품종의 평균, 표준편차 
    print('이름 :', iris.target_names[i])
    print('평균 :', X[Y == i].mean(axis = 0)) 
    print('표준편차 :', X[Y == i].std(axis = 0)) 
    
# 새로운 붓꽃의 데이터를 구한다면 각 품종의 평균 값과 비교하여 가장 비슷한 품종으로 포함 등등 활용
# 데이터의 값과 평균 값의 거리, 차이 만으로 판단하기는 어렵다. 그래서 딥러닝

평균 : [5.006 3.428 1.462 0.246]
표준편차 : [0.34894699 0.37525458 0.17191859 0.10432641]
이름 : setosa
평균 : [5.006 3.428 1.462 0.246]
표준편차 : [0.34894699 0.37525458 0.17191859 0.10432641]
이름 : versicolor
평균 : [5.936 2.77  4.26  1.326]
표준편차 : [0.51098337 0.31064449 0.46518813 0.19576517]
이름 : virginica
평균 : [6.588 2.974 5.552 2.026]
표준편차 : [0.62948868 0.31925538 0.54634787 0.27188968]


In [69]:
# 값을 뺀 cos 값만으로 비교, cos 유사도
# a dot b = |a||b|cos0 , cos0 = a dot b / |a||b|
# np.linalg.norm() 벡터의 크기
# 가장 간단한 매칭 모델, 수리모델
# 트위터, 인스타등 추천 알고리즘에 쓰인다

def cos_sim(a, b) :
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))


sample1 = X[Y == 0][0]
setosa = X[Y == 0].mean(axis = 0)
print(sample1) # Y == 0 품종 중 첫번째 데이터와 Y == 0 품종의 평균값 사이의 유사도
print(setosa)
print(cos_sim(sample1, setosa))

sample2 = X[Y == 2][0]
print(cos_sim(sample2, setosa))

[5.1 3.5 1.4 0.2]
[5.006 3.428 1.462 0.246]
0.9998724340174694
0.868065116199693


In [76]:
# 행열 배열 선형대수 병렬처리가 가능하다.
# 샘플 값, 벡터 값 1:1 비교가 아닌 배열로 비교가 가능하고 빅데이터에 사용된다.

# 150개 꽃 샘플, 4가지 값, 4가지 종 
# (150, 4) dot (4, 1) -> (150, 1) 
# 벡터에 한해서 1, 4 (스칼라가 4개) 는 4, 1 로 볼 수 있다.
print(np.dot(X, setosa))
print(np.dot(X, setosa).shape)
print(np.linalg.norm(X, axis = 1))
print(np.linalg.norm(X, axis = 1).shape)

[39.6246 36.9094 36.4476 35.8966 39.4668 42.9854 36.8034 38.9274 34.0636
 37.3738 41.9582 38.0724 36.3842 33.4426 44.5504 45.9088 42.4006 39.6492
 44.1198 40.8238 41.2222 40.5056 36.8796 39.4514 38.511  37.7024 39.1228
 40.2714 39.7824 36.8862 37.044  40.979  42.3036 44.0266 37.3984 37.8032
 41.4808 38.9416 34.2602 39.428  39.0024 32.3858 34.9458 39.5148 41.4332
 36.4334 40.9454 36.0932 41.4576 38.4384 53.2274 49.956  52.701  41.5852
 49.2316 45.0314 50.1152 37.8272 50.0258 41.333  37.249  46.3288 43.6716
 47.6936 43.5578 50.9442 45.2656 44.5306 45.5268 42.576  47.9654 46.3028
 47.6406 47.3016 48.586  50.1008 51.0012 51.5524 46.9252 42.81   41.5864
 41.4156 44.2874 47.1414 44.2644 48.6638 51.4074 46.1748 44.6316 42.2708
 43.1738 47.8902 44.0908 37.985  43.7494 45.2538 44.9356 47.5848 38.7572
 44.4466 52.2372 46.214  54.969  50.109  51.8438 58.4954 40.0966 56.1384
 51.0326 57.9172 51.4568 49.51   52.8824 44.9062 46.6798 51.3224 51.3068
 61.9092 58.1126 45.2566 54.4102 45.2878 58.432  48

In [87]:
def cos_sim2(sample, standard) :
    return np.dot(sample, standard) / (np.linalg.norm(sample, axis = 1) * np.linalg.norm(standard))

sample = X[Y == 2]
setosa = X[Y == 0].mean(axis = 0)

print(sample)
print(sample[0:150])
cos_sim(sample, setosa)

[[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]
 [7.6 3.  6.6 2.1]
 [4.9 2.5 4.5 1.7]
 [7.3 2.9 6.3 1.8]
 [6.7 2.5 5.8 1.8]
 [7.2 3.6 6.1 2.5]
 [6.5 3.2 5.1 2. ]
 [6.4 2.7 5.3 1.9]
 [6.8 3.  5.5 2.1]
 [5.7 2.5 5.  2. ]
 [5.8 2.8 5.1 2.4]
 [6.4 3.2 5.3 2.3]
 [6.5 3.  5.5 1.8]
 [7.7 3.8 6.7 2.2]
 [7.7 2.6 6.9 2.3]
 [6.  2.2 5.  1.5]
 [6.9 3.2 5.7 2.3]
 [5.6 2.8 4.9 2. ]
 [7.7 2.8 6.7 2. ]
 [6.3 2.7 4.9 1.8]
 [6.7 3.3 5.7 2.1]
 [7.2 3.2 6.  1.8]
 [6.2 2.8 4.8 1.8]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.1]
 [7.2 3.  5.8 1.6]
 [7.4 2.8 6.1 1.9]
 [7.9 3.8 6.4 2. ]
 [6.4 2.8 5.6 2.2]
 [6.3 2.8 5.1 1.5]
 [6.1 2.6 5.6 1.4]
 [7.7 3.  6.1 2.3]
 [6.3 3.4 5.6 2.4]
 [6.4 3.1 5.5 1.8]
 [6.  3.  4.8 1.8]
 [6.9 3.1 5.4 2.1]
 [6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
[[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5

array([0.12605372, 0.11151912, 0.13264584, 0.12091816, 0.12510441,
       0.1411554 , 0.09675721, 0.13546772, 0.1231469 , 0.13976015,
       0.12417054, 0.11947271, 0.12761066, 0.10836327, 0.11264315,
       0.12384622, 0.12380857, 0.14939325, 0.14023167, 0.10920882,
       0.13129739, 0.10928411, 0.14100241, 0.11679417, 0.12958988,
       0.13568297, 0.11606058, 0.1168598 , 0.12147703, 0.13320423,
       0.13520228, 0.15063214, 0.12153639, 0.11814888, 0.11578308,
       0.14071815, 0.12541039, 0.12342778, 0.11529901, 0.12929307,
       0.12776075, 0.12835341, 0.11151912, 0.13079499, 0.12982733,
       0.125463  , 0.1155519 , 0.12286891, 0.12343744, 0.11514939])

In [137]:
# sample 150개에 대해 cos 유사도로 종을 파악하는 코드

def cos_sim2(sample, standard) :   # cos 유사도를 구하는 식
    return np.dot(sample, standard) / (np.linalg.norm(sample, axis = 1) * np.linalg.norm(standard))

sample = X # 150개의 샘플 
setosa = X[Y == 0].mean(axis = 0) # setosa 종의 특성 평균
versicolor = X[Y == 1].mean(axis = 0) # versicolor 종의 특성 평균
virginica = X[Y == 2].mean(axis = 0) # virginica 종의 특성 평균

set_result = cos_sim2(X, setosa)   # 각 샘플과 각 종의 cos 유사도
ver_result = cos_sim2(X, versicolor)
vir_result = cos_sim2(X, virginica)

result = np.stack([set_result, ver_result, vir_result]) # 세 종의 cos 유사도를 한 배열로 결합  stack 이용
# result2 = np.concatenate([set_result, ver_result, vir_result], axis = 1) # (150,3) 의 배열로 합치기 위해서 expand dims을 써야한다 1차원 배열이라서

#np.concatenate((set_result, ver_result), axis = 1)
#print(np.concatenate((set_result, ver_result), axis = 1))

print(np.argmax(result, axis = 0))   # 배열에서 축 기준으로 가장 큰 값의 index 값 반환
print(iris.target) # iris 150개의 샘플의 종 (정답)
print(np.argmax(result, axis = 0) == Y) # 정답 비교 
print(np.sum((iris.target) == np.argmax(result, axis = 0)) / len(Y))   # 정답과 결과(index값)을 비교한 합을 개수로 나눈 정답률



[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 2 1
 1 1 1 1 1 1 1 1 1 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  Tru

* NumPy 연립방정식 풀기 가능, 
* 파이썬의 모든 객체는 얕은 복사, 깊은 복사가 있다. 
    - view, copy

In [148]:
# view (얕은 복사)
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = arr1[1:3] # 슬라이싱할 때 새로운 배열이 생성되는 것이아닌 arr1을 참조하고 있다. arr2는 메모리를 차지하지 않으며 arr1을 보고있다 (view)
print(arr2)
arr2 *= 10  # arr2를 변화하든, arr1을 변화하든 둘 다 영향을 받는다.
print(arr2)
print(arr1)

# 데이터 변환할 때 실수를 해서 원본도 변화 될 수있다. (처음부터 다시 불러와야 된다.)
# 얕은 복사와 깊은 복사는 사용하는 함수에 따라 다르다.
# slicing, indexing, reshape, flatten 은 얕은 복사다.
# 깊은 복사는 대부분의 numpy 연산을 한 이후이다.(일반적으로 연산은 깊은 복사)

# 변화를 원치 않는 경우

arr3 = np.array([1, 2, 3, 4, 5])
arr4 = arr3[1:3].copy()    # .copy() 를 이용하면 view가아닌 새로운 배열을 생성한다.
arr4 *= 10
print(arr4)
print(arr3)

[2 3]
[20 30]
[ 1 20 30  4  5]
[20 30]
[1 2 3 4 5]


# 인플레이스 연산

* 내부에서 일어나는 연산

In [150]:
# 결과는 같지만 과정은 다르다
# 값도 메모리 할당 결과는 같다, 중간에 메모리 할당이 다르다.

arr2 = arr2 * 10 # arr2 * 10을 한 결과가 copy되고(메모리 할당을 받고) arr2에 덮어 씌어진다. copy한 메모리가 해제 된다. 메모리가 넘치면 OOM (out of memory) 라는 경고가 뜬다.
arr2 *= 10 # 인플레이스 연산 메모리 공간 할당없이 연산이 이루어 진다.