# 넘파이 numpy

* 가상환경 만들기
    - conda update -n base conda # 업데이트

    - conda update --all # 설치

    - conda create --name 가상환경이름   # 가상환경 만들기

    - conda activate 가상환경이름  # 가상환경 인증, 활성화

    - conda list # 가상환경 내 라이브러리 목록 보기

    - conda install numpy # 가상환경에 numpy 라이브러리 설치

    - 왜 가상환경을 만들어서 할까?
        -새로운 프로젝트를 나누기 위해, 라이브러리 꼬임을 방지하기 위해 ... 

* 대용량 배열과 행렬 연산에 대한 **고속 연산** 을 지원하는 라이브러리
    - ex. 이미지는 3차원 데이터(높이, 너비, 채널 수), 실제로 가져오면 3차원이 아니며 4차원으로 변경해야 될 일이있다. ... 엄청 많은 데이터 작업이 필요하다는 뜻?
* 딥러닝에 입력으로 들어가는 이미지, 4차원 데이터(batch_size, 높이, 너비, 채널 수)
* 고속 연산과 이미지 러닝에 이용
* 기존 파이썬보다 빠르다. 속도 차이가 크다.
* C 기반으로 연산을 한다. --운영체제와의 리소스 할당에관한 작업이 없어서 빠르다
* 벡터화 연산 
    - ex. list 제곱을 하려면 for문이 돌아가면서 작업, 배열은 각 요소에 바로 제곱
    
* Numpy 배열 생성
    - array() 함수 : 넘파이 배열을 생성하기 위해 사용
    
* NumPy에서 차원의 의미
    - 차원은 배열의 축(axis)의 개수를 의미함
        - 1차원 배열은 하나의 축으로 이루어진 배열 : (3, ), 2차원 : (2, 3), 3차원 (2, 1, 2) ....

* 다양한 NumPy 배열 생성
    - arr = np.array() 로 빈 배열 생성이 불가능하다.
    - zeros() : 모든 요소가 0인 배열을 생성하는 함수
    - ones() : 모든 요소가 1인 배열을 생성하는 함수
    - empty() : 지정된 형태로 새로운 배열을 생성하는 함수
    - full() : 지정된 크기와 값을 가지는 배열을 생성
    - arange() : 지정된 범위 내에서 지정된 간격으로 일정한 값의 배열을 생성 
        - 1차원으로만 생성된다.
    - linspace() : 지정된 범위에서 지정된 개수만큼 동일한 간격으로 일정한 값의 배열을 생성

In [2]:
import numpy as np

In [8]:
import time
# time() 현재 시간
start_time = time.time()   # 시작시간 

numbers = range(1, 10000001)
squares = []

for num in numbers :
    squares.append(num**2)

end_time = time.time()    # 종료시간

print(end_time - start_time)

1.3146486282348633


In [10]:
import time
import numpy as np
# time() 현재 시간
start_time = time.time()   # 시작시간 

numbers = np.arange(1, 10000001)
squares = np.square(numbers)  # square() 제곱을 구하는 함수

end_time = time.time()    # 종료시간

print(end_time - start_time)    # numpy를 이용하면 속도가 빠르다.

0.011288642883300781


In [25]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
arr
print(type(arr))
print(arr)
print("arr의 형태 :", arr.shape) # 배열의 형태
print("arr의 차원수 :", arr.ndim) # 배열의 차원수
print("arr의 내부 원소의 자료형 :", arr.dtype) # 배열 내부 원소의 자료형 
print("arr의 내부 원소의 크기 :", arr.itemsize) # 배열 내부 원소의 크기(바이트 단위)
print("arr의 내부 원소의 개수 :", arr.size) # 배열 내부 원소의 개수

# b = (1) 수식의 소괄호  b = (1, ) 튜플 생성

<class 'numpy.ndarray'>
[1 2 3 4 5]
arr의 형태 : (5,)
arr의 차원수 : 1
arr의 내부 원소의 자료형 : int32
arr의 내부 원소의 크기 : 4
arr의 내부 원소의 개수 : 5


In [27]:
# 열이 하나인 배열 만들기
arr = np.array([[1], [2], [3], [4], [5]]) # 대괄호의 개수로 차원을 알 수 있다.

print(type(arr))
print(arr)
print("arr의 형태 :", arr.shape) # 배열의 형태
print("arr의 차원수 :", arr.ndim) # 배열의 차원수
print("arr의 내부 원소의 자료형 :", arr.dtype) # 배열 내부 원소의 자료형 
print("arr의 내부 원소의 크기 :", arr.itemsize) # 배열 내부 원소의 크기(바이트 단위)
print("arr의 내부 원소의 개수 :", arr.size) # 배열 내부 원소의 개수

<class 'numpy.ndarray'>
[[1]
 [2]
 [3]
 [4]
 [5]]
arr의 형태 : (5, 1)
arr의 차원수 : 2
arr의 내부 원소의 자료형 : int32
arr의 내부 원소의 크기 : 4
arr의 내부 원소의 개수 : 5


In [30]:
# (3,3) 배열 만들기

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(type(arr))
print(arr)
print("arr의 형태 :", arr.shape) # 배열의 형태
print("arr의 차원수 :", arr.ndim) # 배열의 차원수
print("arr의 내부 원소의 자료형 :", arr.dtype) # 배열 내부 원소의 자료형 
print("arr의 내부 원소의 크기 :", arr.itemsize) # 배열 내부 원소의 크기(바이트 단위)
print("arr의 내부 원소의 개수 :", arr.size) # 배열 내부 원소의 개수

<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
arr의 형태 : (3, 3)
arr의 차원수 : 2
arr의 내부 원소의 자료형 : int32
arr의 내부 원소의 크기 : 4
arr의 내부 원소의 개수 : 9


In [32]:
# 3차원 배열

arr = np.array([[[1, 2], 
                 [3, 4]],
                [[5, 6], 
                 [7, 8]]])

print(type(arr))
print(arr)
print("arr의 형태 :", arr.shape) # 배열의 형태
print("arr의 차원수 :", arr.ndim) # 배열의 차원수
print("arr의 내부 원소의 자료형 :", arr.dtype) # 배열 내부 원소의 자료형 
print("arr의 내부 원소의 크기 :", arr.itemsize) # 배열 내부 원소의 크기(바이트 단위)
print("arr의 내부 원소의 개수 :", arr.size) # 배열 내부 원소의 개수

<class 'numpy.ndarray'>
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
arr의 형태 : (2, 2, 2)
arr의 차원수 : 3
arr의 내부 원소의 자료형 : int32
arr의 내부 원소의 크기 : 4
arr의 내부 원소의 개수 : 8


In [40]:
arr = np.array([[[[1, 2], 
                  [3, 4]], 
                 [[5, 6], 
                  [7, 8]]],
                
               [[[9, 10], 
                 [11, 12]], 
                [[13, 14], 
                 [15, 16]]]])

print(type(arr))
print(arr)
print("arr의 형태 :", arr.shape) # 배열의 형태
print("arr의 차원수 :", arr.ndim) # 배열의 차원수
print("arr의 내부 원소의 자료형 :", arr.dtype) # 배열 내부 원소의 자료형 
print("arr의 내부 원소의 크기 :", arr.itemsize) # 배열 내부 원소의 크기(바이트 단위)
print("arr의 내부 원소의 개수 :", arr.size) # 배열 내부 원소의 개수

<class 'numpy.ndarray'>
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
arr의 형태 : (2, 2, 2, 2)
arr의 차원수 : 4
arr의 내부 원소의 자료형 : int32
arr의 내부 원소의 크기 : 4
arr의 내부 원소의 개수 : 16


In [38]:
arr_zeros = np.zeros(3)  # 디폴트로 요소의 값은 모두 실수형으로 채워짐

print(arr_zeros)

arr_zeros = np.zeros((2, 2, 2, 2), dtype=int) # dtype 옵션을 이용하여 요소의 형을 지정할 수 있음

print(arr_zeros)

arr_zeros = np.zeros((2, 2, 2, 2), dtype=str)

print(arr_zeros)

[0. 0. 0.]
[[[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]


 [[[0 0]
   [0 0]]

  [[0 0]
   [0 0]]]]
[[[['' '']
   ['' '']]

  [['' '']
   ['' '']]]


 [[['' '']
   ['' '']]

  [['' '']
   ['' '']]]]


In [44]:
# 초기화하지 않은 메모리
arr_empty = np.empty((2, 3))  # 이전 메모리 공간에 남아있던 쓰레기 값(garbage value)이 보임

print(arr_empty)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
 [6.23043429e-307 2.22526399e-307 2.05837348e-312]]


In [46]:
arr_full = np.full((2, 3, 3), 2)

print(arr_full)

[[[2 2 2]
  [2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]
  [2 2 2]]]


In [55]:
# arange 함수는 1차원 배열로 생성된다.
arr_arange_01 = np.arange(10)

print(arr_arange_01)

arr_arange_02 = np.arange(1, 10, 2)

print(arr_arange_02)

arr_arange_02 = np.arange(1, 11).reshape(2, 5) # 배열 모양 변경

print(arr_arange_02)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [57]:
arr_linspace_01 = np.linspace(0, 1, 5)  # 0과 1사이에서 일정 간격으로 5개 값 생성

print(arr_linspace_01)

[0.   0.25 0.5  0.75 1.  ]


In [11]:
# numpy의 ndarray 사용
import numpy as np
a = np.array([1, 2, 3])
a
a.shape
a.ndim
a.dtype
a.itemsize
a.size



3

In [14]:
a = np.array([1, 2, 3], dtype = 'int32')
b = np.array([4, 5, 6], dtype = 'int64')
a.dtype
b.dtype
c = a + b
c.dtype
c

array([5, 7, 9], dtype=int64)

In [4]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a
b = np.array(range(0, 10))
b
c = np.array(range(0, 10, 2), dtype = 'int64')
c
c.shape
c.ndim
c.dtype
c.size
c.itemsize

a.max()
a.min()
a.mean()

d = np.array([[1, 1], [2, 2], [3, 3]])
d.flatten()   # 배열 평탄화 1차원으로 만들어 준다. 





array([1, 1, 2, 2, 3, 3])

In [11]:
# append() 함수 인자로 입력된 두 배열을 합한다. axis를 통해 축을 명시 한다. (디폴트는 1차원 배열)

a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]]) 
print(np.append(a, b))  # 1차원 배열에 2차원 배열은 더한후 평탄화, 1차원 배열에 2차원 배열을 합하면 오류가 발생???

print(np.append([a], b, axis = 0)) # [a]를 통해 2차원 배열로 만들어라

print(np.random.rand(3, 3)) # rand() 할수를 통해 3, 3 형태의 난수 생성 (0~1사이)

print(np.random.randint(0, 10, size = 10)) # 0에서 10사이 10개의 난수 생성

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0.62240417 0.3006266  0.16671353]
 [0.12447632 0.13155703 0.07680644]
 [0.18035602 0.18454978 0.54759185]]
[7 2 3 1 4 9 1 1 6 3]


In [19]:
a = np.array([23, 45, 67, 7, 2, 30, 34, 82])
a.min()
a.max()
a.mean()

36.25

In [6]:
a = np.array([1, 2, 3])   
b = np.array([4, 5, 6])
c = a + b # shape이 같은 ndarray의 덧셈
c

array([5, 7, 9])

In [7]:
a = np.array([1, 2])
b = np.array([4, 5, 6])
c = a + b # shape이 다른 1차원 배열의 합


ValueError: operands could not be broadcast together with shapes (2,) (3,) 

In [15]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])
a + b # shape이 같은 2차원 배열의 연산
a - b
a * b
a / b

array([[0.1, 0.1],
       [0.1, 0.1]])

In [16]:
# 행렬의 곱 함수 matmul()

np.matmul(a, b)


array([[ 70, 100],
       [150, 220]])

# 배열 인덱싱, 슬라이싱

* 인덱싱 
    - 한 개의 원소를 가져온다
    - arr[1, 1], arr[1][1]   앞에 방식으로 사용하길 권장 뒤에 방식은 2번 인덱싱, 느리다
    - 역순으로 -1, -2 ... 도 가능하다
* 슬라이싱
    - 여러 개의 원소를 한번에 가져온다
    - 전체는 : 혹은 ... 으로 표현 가능
        - 첫 행 
            - arr[0] or arr[0, :]
        - 첫 열
            - arr[:, 0] or arr[..., 0]
    - arr[a:b, c:d]  a부터 b-1 행의 c부터 d-1 열을 슬라이싱
    - arr[a:b:c, d:e:f] a부터 b-1행을 c 간격으로 , d부터 e-1 열을 f 간격으로
    - arr[::-1, :] 행을 역순으로

* 인덱싱은 차원을 자동으로 낮춰서 변환해서 반환, 슬라이싱은 차원을 유지하며 반환 

In [18]:
import numpy as np

arr = np.arange(1, 10)

print(arr)
print(arr[3])

arr[0] = 10

print(arr)

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

print(arr[..., 0])
print(arr[0:3:2, 0:3:2])
print(arr[::-1, :])
print(arr[:, ::-1])
print(arr[::-1, ::-1])

[1 2 3 4 5 6 7 8 9]
4
[10  2  3  4  5  6  7  8  9]
[ 1  5  9 13]
[[ 1  3]
 [ 9 11]]
[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]
[[16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
